# Generated by Django 5.0.7 on 2024-07-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_amount_alter_expenseshare_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseShare',
        ),
    ]
