# Generated by Django 5.0.7 on 2024-08-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_delete_expenseshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.expense'),
            preserve_default=False,
        ),
    ]
