# Generated by Django 5.0.7 on 2024-08-02 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_transaction_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(related_name='participants_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
